/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAssignmentsRouteImport } from './routes/_authenticated/admin/assignments'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'
import { Route as AuthenticatedAdminInternsRouteImport } from './routes/_authenticated/admin/interns'
import { Route as AuthenticatedAdminOnboardedRouteImport } from './routes/_authenticated/admin/onboarded'
import { Route as AuthenticatedAdminSurveyCompletedRouteImport } from './routes/_authenticated/admin/survey-completed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAssignmentsRoute =
  AuthenticatedAdminAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInternsRoute =
  AuthenticatedAdminInternsRouteImport.update({
    id: '/interns',
    path: '/interns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOnboardedRoute =
  AuthenticatedAdminOnboardedRouteImport.update({
    id: '/onboarded',
    path: '/onboarded',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSurveyCompletedRoute =
  AuthenticatedAdminSurveyCompletedRouteImport.update({
    id: '/survey-completed',
    path: '/survey-completed',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/my': typeof AuthenticatedMyRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/interns': typeof AuthenticatedAdminInternsRoute
  '/admin/onboarded': typeof AuthenticatedAdminOnboardedRoute
  '/admin/survey-completed': typeof AuthenticatedAdminSurveyCompletedRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my': typeof AuthenticatedMyRoute
  '/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/interns': typeof AuthenticatedAdminInternsRoute
  '/admin/onboarded': typeof AuthenticatedAdminOnboardedRoute
  '/admin/survey-completed': typeof AuthenticatedAdminSurveyCompletedRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/my': typeof AuthenticatedMyRoute
  '/_authenticated/admin/assignments': typeof AuthenticatedAdminAssignmentsRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/interns': typeof AuthenticatedAdminInternsRoute
  '/_authenticated/admin/onboarded': typeof AuthenticatedAdminOnboardedRoute
  '/_authenticated/admin/survey-completed': typeof AuthenticatedAdminSurveyCompletedRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/my'
    | '/admin/assignments'
    | '/admin/companies'
    | '/admin/interns'
    | '/admin/onboarded'
    | '/admin/survey-completed'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my'
    | '/admin/assignments'
    | '/admin/companies'
    | '/admin/interns'
    | '/admin/onboarded'
    | '/admin/survey-completed'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/my'
    | '/_authenticated/admin/assignments'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/interns'
    | '/_authenticated/admin/onboarded'
    | '/_authenticated/admin/survey-completed'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/assignments': {
      id: '/_authenticated/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AuthenticatedAdminAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/interns': {
      id: '/_authenticated/admin/interns'
      path: '/interns'
      fullPath: '/admin/interns'
      preLoaderRoute: typeof AuthenticatedAdminInternsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/onboarded': {
      id: '/_authenticated/admin/onboarded'
      path: '/onboarded'
      fullPath: '/admin/onboarded'
      preLoaderRoute: typeof AuthenticatedAdminOnboardedRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/survey-completed': {
      id: '/_authenticated/admin/survey-completed'
      path: '/survey-completed'
      fullPath: '/admin/survey-completed'
      preLoaderRoute: typeof AuthenticatedAdminSurveyCompletedRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAssignmentsRoute: typeof AuthenticatedAdminAssignmentsRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminInternsRoute: typeof AuthenticatedAdminInternsRoute
  AuthenticatedAdminOnboardedRoute: typeof AuthenticatedAdminOnboardedRoute
  AuthenticatedAdminSurveyCompletedRoute: typeof AuthenticatedAdminSurveyCompletedRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAssignmentsRoute: AuthenticatedAdminAssignmentsRoute,
    AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
    AuthenticatedAdminInternsRoute: AuthenticatedAdminInternsRoute,
    AuthenticatedAdminOnboardedRoute: AuthenticatedAdminOnboardedRoute,
    AuthenticatedAdminSurveyCompletedRoute:
      AuthenticatedAdminSurveyCompletedRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMyRoute: typeof AuthenticatedMyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMyRoute: AuthenticatedMyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
